# Generated by Django 6.1 on 2026-09-01 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decks', '0002_deck_visibility'),
        ('notes', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='decks.deck')),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='notes.note')),
            ],
        ),
    ]
