# Generated by Django 6.1 on 2026-09-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstate',
            name='scheduled_days',
            field=models.FloatField(default=0.0),
        ),
    ]
