# Generated by Django 6.1 on 2026-09-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewstate_scheduled_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='elapsed_days',
            field=models.FloatField(default=0.0),
        ),
    ]
