# Generated by Django 6.1 on 2026-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewlog_elapsed_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='new_scheduled_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='previous_scheduled_days',
            field=models.FloatField(default=0.0),
        ),
    ]
